name: wee-slack
on: [push, pull_request]

jobs:
  test:
    if: >
      github.event_name == 'push' || (
        github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name != github.repository
      )

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v3

      - run: poetry install --all-extras

      - run: poetry run ruff format --check

      - run: poetry run ruff check

      - run: poetry run pyright

      - run: poetry run pytest tests

  build:
    if: >
      github.event_name == 'push' || (
        github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name != github.repository
      )

    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: abatilo/actions-poetry@v3
      - run: poetry install

      - name: Install WeeChat, tmux and python3-websocket
        run: |
          sudo apt-get update
          sudo apt-get install weechat-headless tmux python3-websocket

      - run: ./build.sh

      - name: Load slack.py in WeeChat
        run: |
          WEECHAT_DIR=$(mktemp -d)
          tmux new-session -d "weechat-headless --dir $WEECHAT_DIR -r '/script load $PWD/build/slack.py; /quit'"
          while pidof -q tmux; do :; done
          cat $WEECHAT_DIR/logs/core.weechat.weechatlog
          grep -q 'python: registered script "slack"' $WEECHAT_DIR/logs/core.weechat.weechatlog

      - uses: actions/upload-artifact@v4
        with:
          name: slack.py
          path: build/slack.py

      - uses: pyTooling/Actions/releaser@r1
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          files: |
            build/slack.py
